### ISSUE TITLE
Ler resultados de anos anteriores

### ISSUE THREAD

**Issue by glaucocustodio** [eudesrodrigo/brFinance#10]
Oi @eudesrodrigo, primeiramente quero te agradecer por disponibilizar essa ferramenta publicamente.

Atualmente ela só retorna o ano mais recente (em vermelho na imagem) certo? Você aceitaria um PR para retornar todos os anos (em azul)?

![Screenshot 2022-01-14 at 19 53 57](https://user-images.githubusercontent.com/1907408/149576979-dc901dba-9d5b-4e6c-820a-595e0ae532a8.png)

**Comment by eudesrodrigo** [comment]
Bom dia, @glaucocustodio tudo certo?
Eu que agradeço a colaboração! Fico feliz demais!
Eu nã coloquei os outros dados no dataframe pq você consegue o histórico pela biblioteca. Tem um parâmetro que é opção para pegar apenas o último resultado ou para pegar o histórico entre as datas colocadas. Isso não serviria? Você recupera os dados e depois faz um merge entre as datas e contas. Me diz o que você acha e avançamos caso necessário, mas foi proposital. Fala comigo se tier alguma dúvida, te add no LinkedIn.

**Comment by joaomj** [comment]
Eudes, posso tirar uma dúvida a respeito da execução do código? Aqui ou no Linkedin? Obrigado.

**Comment by glaucocustodio** [comment]
> Tem um parâmetro que é opção para pegar apenas o último resultado ou para pegar o histórico entre as datas colocadas. Isso não serviria?
Não serve, eu adicionei o que eu preciso aqui https://github.com/eudesrodrigo/brFinance/pull/13
