### ISSUE TITLE
Lib\site-packages\brFinance

### ISSUE THREAD

**Issue by olafotte** [eudesrodrigo/brFinance#12]
Olá Eudes,

Parabéns pela idéia. Tentei installar usando o pip install e ocorreu um problema na hora de executar o código. Descobri que a importação não funciona no exemplo atual porque no código chama "from br**f**inance import CVMAsyncBackend" e observando a pasta Lib\site-packages\br**F**inance vi que o nome da pasta é brFinance. Eu renomei na minha máquina a pasta para Lib\site-packages\br**f**inance e aí rodou o programa.

**Comment by eudesrodrigo** [comment]
Perfeito, meu amigo! Obrigado pelo aviso.
Acabei de subir nova versão corrigindo isso.
Obrigado mesmo! =D
