### ISSUE TITLE
Importação da classe CVMAsyncBackend

### ISSUE THREAD

**Issue by MarcosRMG** [eudesrodrigo/brFinance#23]
Olá

Obtive o seguinte erro na importação da classe CVMAsyncBackend

AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'

![image](https://github.com/eudesrodrigo/brFinance/assets/67550825/90cd59f4-83e2-44d4-8967-23a931d5ad1a)

Fiz o upgrade da biblioteca urllib3 mas já está na última versão. 
![image](https://github.com/eudesrodrigo/brFinance/assets/67550825/5399ff71-0b5d-4e48-985f-b2698f81ff10)

Obrigado

**Comment by joaovbezerra1990** [comment]
Usei isso e resolveu, parece que houve algumas mudanças severas nessa urllib3, mas a versao 1.26 tem suporte por alguns anos ainda.
requirements.txt
urllib3==1.26

**Comment by MarcosRMG** [comment]
Obrigado @joaovbezerra1990
